# Generated by Django 6.0.5 on 2026-06-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_review_alter_worksimages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
